### ISSUE TITLE
muted example plays with sound

### ISSUE THREAD

**Issue by Haroenv** [AKHXtern/paper-video#1]
Safari 9.1.1

**Comment by dreammmr** [comment]
It looks like Safari does not support this attribute. It's not listed among the supported attributes in Apple's documentation. It's left out of the browser compatibility table on MDN. Testing shows that setting the muted property on the DOM object does not add the attribute. For comparison, setting controls to true does set the controls attribute.

I'm afraid you need to use Javascript for this. (or no! :) I will add some trick for muted on desktop Safari )

It's worth noting that Mobile Safari on iOS ignores both volume and muted, even if you use Javascript. The only way to control volume of a video in that case is with the hardware volume controls.

**Comment by Haroenv** [comment]
weird, I used muted video on Safari on for example my 404 page: https://haroen.me/404/ (source: https://github.com/Haroenv/haroenv.github.io/blob/master/404.html) which starts out as muted.

**Comment by dreammmr** [comment]
The issue was, that I was binding a properties into a "video" tag, but there was no need. Safari was getting mad from it :) So it's fixed now.
