### ISSUE TITLE
Fullscreen toggle on double click

### ISSUE THREAD

**Issue by gormat** [AKHXtern/paper-video#7]
Fullscreen toggle on double click

**Comment by ccjmne** [comment]
I implemented that as follows:
> Tap events are delayed by 300ms before triggering a play/pause toggle. If another tap occurs during that time period, the fullscreen mode is de/activated instead.

Seems to me that it's the way Youtube handles it too.

--
Since it has been merged in, I believe we can close this issue.

**Comment by gormat** [comment]
ok @ccjmne Thank you.
